### ISSUE TITLE
An issue encountered in file 3DMMExtract/Coarse/util/load_mats.py 

### ISSUE THREAD

**Issue by 904763189cy** [theEricMa/OTAvatar_processing#3]
Missing function LoadExpBasis.
But I found this function in project ( https://github.com/sicxu/Deep3DFaceRecon_pytorch).

def LoadExpBasis(bfm_folder='BFM'):
    n_vertex = 53215
    Expbin = open(osp.join(bfm_folder, 'Exp_Pca.bin'), 'rb')
    exp_dim = array('i')
    exp_dim.fromfile(Expbin, 1)
    expMU = array('f')
    expPC = array('f')
    expMU.fromfile(Expbin, 3*n_vertex)
    expPC.fromfile(Expbin, 3*exp_dim[0]*n_vertex)
    Expbin.close()

    expPC = np.array(expPC)
    expPC = np.reshape(expPC, [exp_dim[0], -1])
    expPC = np.transpose(expPC)

    expEV = np.loadtxt(osp.join(bfm_folder, 'std_exp.txt'))

    return expPC, expEV

Is this correct?

**Comment by theEricMa** [comment]
You're right, our intention is to streamline the script by removing any unnecessary code. However, it appears that in doing so, we may have accidentally removed come important code as well. We will revise the script to make it more concise while ensuring no vital functionality is lost. Thank you for catching this issue - your feedback will help us improve the script moving forward.

**Comment by Thisisaname1125** [comment]
> Missing function LoadExpBasis. But I found this function in project ( https://github.com/sicxu/Deep3DFaceRecon_pytorch).
> ```
> def LoadExpBasis(bfm_folder='BFM'):
   >n_vertex = 53215 
  >Expbin = open(osp.join(bfm_folder, 'Exp_Pca.bin'), 'rb')
   >exp_dim = array('i') exp_dim.fromfile(Expbin, 1) 
 > expMU = array('f') 
 > expPC = array('f') 
  >expMU.fromfile(Expbin, 3_n_vertex)
  > expPC.fromfile(Expbin, 3_exp_dim[0]*n_vertex)
   >Expbin.close()
> expPC = np.array(expPC)
> expPC = np.reshape(expPC, [exp_dim[0], -1])
> expPC = np.transpose(expPC)
> 
> expEV = np.loadtxt(osp.join(bfm_folder, 'std_exp.txt'))
> 
> return expPC, expEV
> ```
> 
> Is this correct?

hello, when i run this code. 
```
def transferBFM09(bfm_folder='BFM'):
    print('Transfer BFM09 to BFM_model_front......')
    original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
    shapePC = original_BFM['shapePC']  # shape basis
    shapeEV = original_BFM['shapeEV']  # corresponding eigen value
    shapeMU = original_BFM['shapeMU']  # mean face
    texPC = original_BFM['texPC']  # texture basis
    texEV = original_BFM['texEV']  # eigen value
    texMU = original_BFM['texMU']  # mean texture

    expPC, expEV = LoadExpBasis()
```
i got 
```
Traceback (most recent call last):
  File "/mnt/mfs/zhikun.zhao/otavatar/OTAvatar_processing-main/3DMMExtract/Coarse/models/bfm.py", line 40, in __init__
    transferBFM09(bfm_folder)
  File "/mnt/mfs/zhikun.zhao/otavatar/OTAvatar_processing-main/3DMMExtract/Coarse/util/load_mats.py", line 10, in transferBFM09
    original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
  File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/opt/conda/envs/otavatar/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'BFM/01_MorphableModel.mat'
```
could you tell me where to get the 01_MorphableModel.mat?

**Comment by Thisisaname1125** [comment]
Got it! It can be downloaded in [https://huggingface.co/vinthony/SadTalker/blob/main/BFM_Fitting/01_MorphableModel.mat](https://huggingface.co/vinthony/SadTalker/blob/main/BFM_Fitting/01_MorphableModel.mat)

**Comment by 904763189cy** [comment]
> > Missing function LoadExpBasis. But I found this function in project ( https://github.com/sicxu/Deep3DFaceRecon_pytorch).
> > ```
> > def LoadExpBasis(bfm_folder='BFM'):
> > n_vertex = 53215 
> > Expbin = open(osp.join(bfm_folder, 'Exp_Pca.bin'), 'rb')
> > exp_dim = array('i') exp_dim.fromfile(Expbin, 1) 
> > expMU = array('f') 
> > expPC = array('f') 
> > expMU.fromfile(Expbin, 3_n_vertex)
> > expPC.fromfile(Expbin, 3_exp_dim[0]*n_vertex)
> > Expbin.close()
> > expPC = np.array(expPC)
> > expPC = np.reshape(expPC, [exp_dim[0], -1])
> > expPC = np.transpose(expPC)
> > 
> > expEV = np.loadtxt(osp.join(bfm_folder, 'std_exp.txt'))
> > 
> > return expPC, expEV
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this correct?
> 
> hello, when i run this code.
> 
> ```
> def transferBFM09(bfm_folder='BFM'):
>     print('Transfer BFM09 to BFM_model_front......')
>     original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
>     shapePC = original_BFM['shapePC']  # shape basis
>     shapeEV = original_BFM['shapeEV']  # corresponding eigen value
>     shapeMU = original_BFM['shapeMU']  # mean face
>     texPC = original_BFM['texPC']  # texture basis
>     texEV = original_BFM['texEV']  # eigen value
>     texMU = original_BFM['texMU']  # mean texture
> 
>     expPC, expEV = LoadExpBasis()
> ```
> 
> i got
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/mfs/zhikun.zhao/otavatar/OTAvatar_processing-main/3DMMExtract/Coarse/models/bfm.py", line 40, in __init__
>     transferBFM09(bfm_folder)
>   File "/mnt/mfs/zhikun.zhao/otavatar/OTAvatar_processing-main/3DMMExtract/Coarse/util/load_mats.py", line 10, in transferBFM09
>     original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
>   File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
>     with _open_file_context(file_name, appendmat) as f:
>   File "/opt/conda/envs/otavatar/lib/python3.9/contextlib.py", line 119, in __enter__
>     return next(self.gen)
>   File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
>     f, opened = _open_file(file_like, appendmat, mode)
>   File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
>     return open(file_like, mode), True
> FileNotFoundError: [Errno 2] No such file or directory: 'BFM/01_MorphableModel.mat'
> ```
> 
> could you tell me where to get the 01_MorphableModel.mat?

你看函数名写着BFM09，这个文件01_MorphableModel.mat应该跟BFM09有关，我上面所提的链接 https://github.com/sicxu/Deep3DFaceRecon_pytorch在readme的Inference with a pre-trained model就提到这个.mat，还给了下载链接，我刚刚看了，我也不知道下载，我都忘了当时怎么弄到这个mat文件的。肯定不止Deep3DFaceRecon_pytorch用过BFM09，所以在GitHub全网搜BFM09就行了，我刚刚找到了一个项目https://github.com/rlgnswk/NeRFFaceSpeech_Code使用了BFM09，这个项目给了01_MorphableModel.mat，你可以看NeRFFaceSpeech_Code的readme。NeRFFaceSpeech_Code给的01_MorphableModel.mat下载链接是https://drive.google.com/drive/folders/1CxZuMICBgcEbCfRMhh4KRHChrNG3tyJF。虽然找到了这个文件，但是我不保证两个项目用的都是同一个文件。我并不熟悉这个领域。

**Comment by Thisisaname1125** [comment]
> > > Missing function LoadExpBasis. But I found this function in project ( https://github.com/sicxu/Deep3DFaceRecon_pytorch).
> > > ```
> > > def LoadExpBasis(bfm_folder='BFM'):
> > > n_vertex = 53215 
> > > Expbin = open(osp.join(bfm_folder, 'Exp_Pca.bin'), 'rb')
> > > exp_dim = array('i') exp_dim.fromfile(Expbin, 1) 
> > > expMU = array('f') 
> > > expPC = array('f') 
> > > expMU.fromfile(Expbin, 3_n_vertex)
> > > expPC.fromfile(Expbin, 3_exp_dim[0]*n_vertex)
> > > Expbin.close()
> > > expPC = np.array(expPC)
> > > expPC = np.reshape(expPC, [exp_dim[0], -1])
> > > expPC = np.transpose(expPC)
> > > 
> > > expEV = np.loadtxt(osp.join(bfm_folder, 'std_exp.txt'))
> > > 
> > > return expPC, expEV
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is this correct?
> > 
> > 
> > hello, when i run this code.
> > ```
> > def transferBFM09(bfm_folder='BFM'):
> >     print('Transfer BFM09 to BFM_model_front......')
> >     original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
> >     shapePC = original_BFM['shapePC']  # shape basis
> >     shapeEV = original_BFM['shapeEV']  # corresponding eigen value
> >     shapeMU = original_BFM['shapeMU']  # mean face
> >     texPC = original_BFM['texPC']  # texture basis
> >     texEV = original_BFM['texEV']  # eigen value
> >     texMU = original_BFM['texMU']  # mean texture
> > 
> >     expPC, expEV = LoadExpBasis()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i got
> > ```
> > Traceback (most recent call last):
> >   File "/mnt/mfs/zhikun.zhao/otavatar/OTAvatar_processing-main/3DMMExtract/Coarse/models/bfm.py", line 40, in __init__
> >     transferBFM09(bfm_folder)
> >   File "/mnt/mfs/zhikun.zhao/otavatar/OTAvatar_processing-main/3DMMExtract/Coarse/util/load_mats.py", line 10, in transferBFM09
> >     original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
> >   File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
> >     with _open_file_context(file_name, appendmat) as f:
> >   File "/opt/conda/envs/otavatar/lib/python3.9/contextlib.py", line 119, in __enter__
> >     return next(self.gen)
> >   File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
> >     f, opened = _open_file(file_like, appendmat, mode)
> >   File "/opt/conda/envs/otavatar/lib/python3.9/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
> >     return open(file_like, mode), True
> > FileNotFoundError: [Errno 2] No such file or directory: 'BFM/01_MorphableModel.mat'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > could you tell me where to get the 01_MorphableModel.mat?
> 
> 你看函数名写着BFM09，这个文件01_MorphableModel.mat应该跟BFM09有关，我上面所提的链接 [https://github.com/sicxu/Deep3DFaceRecon_pytorch在readme的Inference](https://github.com/sicxu/Deep3DFaceRecon_pytorch%E5%9C%A8readme%E7%9A%84Inference) with a pre-trained model就提到这个.mat，还给了下载链接，我刚刚看了，我也不知道下载，我都忘了当时怎么弄到这个mat文件的。肯定不止Deep3DFaceRecon_pytorch用过BFM09，所以在GitHub全网搜BFM09就行了，我刚刚找到了一个项目[https://github.com/rlgnswk/NeRFFaceSpeech_Code使用了BFM09，这个项目给了01_MorphableModel.mat，你可以看NeRFFaceSpeech_Code的readme。NeRFFaceSpeech_Code给的01_MorphableModel.mat下载链接是https://drive.google.com/drive/folders/1CxZuMICBgcEbCfRMhh4KRHChrNG3tyJF。虽然找到了这个文件，但是我不保证两个项目用的都是同一个文件。我并不熟悉这个领域。](https://github.com/rlgnswk/NeRFFaceSpeech_Code%E4%BD%BF%E7%94%A8%E4%BA%86BFM09%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%BB%99%E4%BA%8601_MorphableModel.mat%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E7%9C%8BNeRFFaceSpeech_Code%E7%9A%84readme%E3%80%82NeRFFaceSpeech_Code%E7%BB%99%E7%9A%8401_MorphableModel.mat%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5%E6%98%AFhttps://drive.google.com/drive/folders/1CxZuMICBgcEbCfRMhh4KRHChrNG3tyJF%E3%80%82%E8%99%BD%E7%84%B6%E6%89%BE%E5%88%B0%E4%BA%86%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%EF%BC%8C%E4%BD%86%E6%98%AF%E6%88%91%E4%B8%8D%E4%BF%9D%E8%AF%81%E4%B8%A4%E4%B8%AA%E9%A1%B9%E7%9B%AE%E7%94%A8%E7%9A%84%E9%83%BD%E6%98%AF%E5%90%8C%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E3%80%82%E6%88%91%E5%B9%B6%E4%B8%8D%E7%86%9F%E6%82%89%E8%BF%99%E4%B8%AA%E9%A2%86%E5%9F%9F%E3%80%82)

谢谢你！我刚刚就是全网搜到的，有人扔到huggingface网站上了。：）
